<a href="https://colab.research.google.com/github/ThirumalReddyPeddi/Numerical-Programming-in-Python---Web-Scraping.ipynb/blob/main/03_Movie_DataFrame_Creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Now Creating Movies DataFrame**

In [ ]:
# Verify that all scraped data lists have the same number of elements
# This is an important validation step before creating the DataFrame.
# Each list should have one entry for every movie scraped.

print("Total Movie Titles:", len(movie_titles))
print("Total Release Years:", len(release_years))
print("Total Movie Genres:", len(movie_genres))
print("Total IMDb Ratings:", len(imdb_ratings))
print("Total Movie Runtimes:", len(movie_runtime))
print("Total Age Ratings:", len(age_ratings))
print("Total Production Countries:", len(production_countries))
print("Total Primary OTT Platforms:", len(primary_ott))
print("Total Movie URLs:", len(movie_urls))

Total Movie Titles: 105
Total Release Years: 105
Total Movie Genres: 105
Total IMDb Ratings: 105
Total Movie Runtimes: 105
Total Age Ratings: 105
Total Production Countries: 105
Total Primary OTT Platforms: 105
Total Movie URLs: 105

In [ ]:
# Import the Pandas library
# Pandas is used to create and manipulate tabular data structures called DataFrames
import pandas as pd

# Create a DataFrame by combining all the scraped movie information
# Each key in the dictionary represents a column name,
# and the corresponding list contains the values for that column
movies_df = pd.DataFrame({

    # List of movie titles extracted from the movie pages
    "Movie_Title": movie_titles,

    # List of movie release years
    "Release_Year": release_years,

    # List of movie genres
    "Genres": movie_genres,

    # List of URLs corresponding to each movie page
    "URLs": movie_urls,

    # List of IMDb ratings for each movie
    "IMDb_Rating": imdb_ratings,

    # List of movie runtimes
    "Runtime": movie_runtime,

    # List of age ratings (e.g., U, U/A, A, PG-13)
    "Age_Rating": age_ratings,

    # List of production countries for each movie
    "Production_Country": production_countries,

    # List of primary OTT streaming platforms
    # where each movie is available
    "OTT Streaming_Service": primary_ott
})

# Display the first five rows of the DataFrame
# This helps verify that the scraped data has been correctly stored
movies_df.head()

,Movie_Title,Release_Year,Genres,URLs,IMDb_Rating,Runtime,Age_Rating,Production_Country,OTT Streaming_Service
0,Crush(2009),2009,"Horror, Drama, Horror Thriller, Mystery Thriller",https://www.justwatch.com/in/movie/crush-2009,4.2,1h 22min,None,Australia,Apple TV Store
1,Taya(2021),2021,"Mystery & Thriller, Crime, Drama, Romantic Thr...",https://www.justwatch.com/in/movie/taya-2021,4.7,1h 43min,None,Philippines,Amazon Video
2,Kara(2026),2026,"Drama, Mystery & Thriller, Crime, Heist",https://www.justwatch.com/in/movie/kara,7.1,2h 41min,UA16+,India,Netflix
3,Hai Jawani Toh Ishq Hona Hai(2026),2026,"Romance, Comedy",https://www.justwatch.com/in/movie/hai-jawani-...,None,2h 16min,UA16+,India,Crunchyroll
4,Stay Lost(2023),2023,Romance,https://www.justwatch.com/in/movie/stay-lost,None,12min,None,United States,Crunchyroll

In [ ]:
import pandas as pd

movies_df = pd.DataFrame({
    "Movie_Title": movie_titles,
    "Release_Year": release_years,
    "Genres": movie_genres,
    'URLs':movie_urls,
    "IMDb_Rating": imdb_ratings,
    "Runtime": movie_runtime,
    "Age_Rating": age_ratings,
    "Production_Country": production_countries,
    "OTT Streaming_Service": primary_ott
})

# Display the complete DataFrame
# Each row represents one movie and its associated details
movies_df

,Movie_Title,Release_Year,Genres,URLs,IMDb_Rating,Runtime,Age_Rating,Production_Country,OTT Streaming_Service
0,Crush(2009),2009,"Horror, Drama, Horror Thriller, Mystery Thriller",https://www.justwatch.com/in/movie/crush-2009,4.2,1h 22min,None,Australia,Apple TV Store
1,Taya(2021),2021,"Mystery & Thriller, Crime, Drama, Romantic Thr...",https://www.justwatch.com/in/movie/taya-2021,4.7,1h 43min,None,Philippines,Amazon Video
2,Kara(2026),2026,"Drama, Mystery & Thriller, Crime, Heist",https://www.justwatch.com/in/movie/kara,7.1,2h 41min,UA16+,India,Netflix
3,Hai Jawani Toh Ishq Hona Hai(2026),2026,"Romance, Comedy",https://www.justwatch.com/in/movie/hai-jawani-...,None,2h 16min,UA16+,India,Crunchyroll
4,Stay Lost(2023),2023,Romance,https://www.justwatch.com/in/movie/stay-lost,None,12min,None,United States,Crunchyroll
...,...,...,...,...,...,...,...,...,...
100,Send Help(2026),2026,"Horror, Mystery & Thriller, Comedy, Horror Thr...",https://www.justwatch.com/in/movie/send-help,7.2,1h 53min,A,United States,JioHotstar
101,The Maid(2014),2014,"Romance, Drama, Romantic Drama",https://www.justwatch.com/in/movie/the-maid,4.4,1h 39min,None,United Kingdom,JustWatch
102,Obsession(2015),2015,"Mystery & Thriller, Romance, Drama, Made in Eu...",https://www.justwatch.com/in/movie/rendez-vous,5.6,1h 40min,None,Netherlands,Amazon Prime Video
103,The Kamasutra Garden(2020),2020,"Romance, Romantic Drama",https://www.justwatch.com/in/movie/the-kamasut...,3.9,2h 0min,None,United States,Apple TV Store
104,Youth(2026),2026,"Comedy, Kids & Family, Romance, Drama, Dramedy",https://www.justwatch.com/in/movie/youth-2026,8.1,2h 20min,UA13+,India,Netflix

In [ ]:
# Display a concise summary of the DataFrame
# The info() method provides important information about the dataset,
# including the number of rows, column names, data types,
# non-null values, and memory usage.

movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Movie_Title            105 non-null    object
 1   Release_Year           96 non-null     object
 2   Genres                 103 non-null    object
 3   URLs                   105 non-null    object
 4   IMDb_Rating            77 non-null     object
 5   Runtime                103 non-null    object
 6   Age_Rating             43 non-null     object
 7   Production_Country     105 non-null    object
 8   OTT Streaming_Service  105 non-null    object
dtypes: object(9)
memory usage: 7.5+ KB

In [ ]:
# Save the movies DataFrame as a CSV file
# The file will be created in the current working directory.
# Setting index=False prevents Pandas from writing the row index
# as an additional column in the CSV file.

movies_df.to_csv(
    "Movies_Dataa.csv",
    index=False
)

# Display a confirmation message after the file is successfully saved
print("Movies_Data.csv saved successfully")

Movies_Data.csv saved successfully

In [ ]:
# Convert the 'IMDb_Rating' column from text (string) to numeric format
# The 'errors="coerce"' parameter replaces any invalid or missing values
# with NaN (Not a Number), preventing conversion errors.

movies_df["IMDb_Rating"] = pd.to_numeric(
    movies_df["IMDb_Rating"],
    errors="coerce"
)

# Filter the DataFrame to include only movies
# with an IMDb rating of 7 or higher.

filtered_df = movies_df[
    movies_df["IMDb_Rating"] >= 7
]

# Display the filtered DataFrame
# The output will contain only movies that satisfy the IMDb rating condition.

filtered_df

,Movie_Title,Release_Year,Genres,URLs,IMDb_Rating,Runtime,Age_Rating,Production_Country,OTT Streaming_Service
2,Kara(2026),2026,"Drama, Mystery & Thriller, Crime, Heist",https://www.justwatch.com/in/movie/kara,7.1,2h 41min,UA16+,India,Netflix
17,Marty Supreme(2025),2025,"Drama, Sport, Mystery & Thriller, Dramedy",https://www.justwatch.com/in/movie/marty-supreme,7.8,2h 29min,A,"Finland, United States",Apple TV Store
29,Deiva Thirumagal(2011),2011,"Drama, Kids & Family, Bollywood",https://www.justwatch.com/in/movie/deiva-thiru...,8.2,2h 42min,None,India,Sun Nxt
32,Dos Otoños en Paris(2020),2020,"Drama, Mystery & Thriller, Romance, Emotional ...",https://www.justwatch.com/in/movie/two-autumns...,7.0,1h 40min,None,"Canada, Venezuela",Crunchyroll
34,Dhurandhar The Revenge(2026),2026,"Action & Adventure, Crime, Mystery & Thriller",https://www.justwatch.com/in/movie/dhurandhar-...,8.7,3h 50min,A,India,JioHotstar
36,Hokum(2026),2026,"Horror, Horror Thriller",https://www.justwatch.com/in/movie/hokum-2026,8.0,1h 41min,A,"United Arab Emirates, United States, Ireland",Crunchyroll
38,The Punisher: One Last Kill(2026),2026,"Action & Adventure, Drama, Crime, Mystery & Th...",https://www.justwatch.com/in/movie/the-punishe...,7.1,51min,None,United States,JioHotstar
44,Project Hail Mary(2026),2026,"Science-Fiction, Action & Adventure, Drama, My...",https://www.justwatch.com/in/movie/project-hai...,8.5,2h 37min,UA13+,United States,Apple TV Store
50,Dhurandhar(2025),2025,"Action & Adventure, Crime, Mystery & Thriller,...",https://www.justwatch.com/in/movie/dhurandhar-...,8.3,3h 32min,A,India,Netflix
57,Sambhavam Adhyayam Onnu(2026),2026,"Fantasy, Mystery & Thriller, Drama, Psychologi...",https://www.justwatch.com/in/movie/sambhavam-a...,7.3,2h 7min,UA13+,India,JioHotstar
71,K.G.F: Chapter 2(2022),2022,"Crime, Drama, Mystery & Thriller, Action & Adv...",https://www.justwatch.com/in/movie/k-g-f-chapt...,8.2,2h 46min,UA,India,Amazon Prime Video
72,Obsession(2026),2026,"Mystery & Thriller, Horror, Horror Thriller",https://www.justwatch.com/in/movie/obsession-2026,8.1,1h 48min,A,"United States, United Kingdom",Crunchyroll
80,Demon Slayer: Kimetsu no Yaiba Infinity Castle...,2025,"Fantasy, Action & Adventure, Mystery & Thrille...",https://www.justwatch.com/in/movie/demon-slaye...,8.4,2h 35min,UA13+,Japan,Crunchyroll
85,KD: The Devil(2025),2025,"Action & Adventure, Crime, Fantasy, History, A...",https://www.justwatch.com/in/movie/kd-the-devil,7.4,2h 5min,None,India,Crunchyroll
86,Dacoit: A Love Story(2026),2026,"Romance, Mystery & Thriller, Action & Adventur...",https://www.justwatch.com/in/movie/dacoit-a-lo...,7.6,2h 29min,UA,India,Amazon Prime Video
91,"The Gangster, the Cop, the Devil(2019)",2019,"Action & Adventure, Crime, Mystery & Thriller,...",https://www.justwatch.com/in/movie/the-gangste...,7.0,1h 50min,None,South Korea,Amazon Prime Video
95,Hoppers(2026),2026,"Action & Adventure, Animation, Comedy, Kids & ...",https://www.justwatch.com/in/movie/hoppers,7.6,1h 44min,UA7+,United States,JioHotstar
100,Send Help(2026),2026,"Horror, Mystery & Thriller, Comedy, Horror Thr...",https://www.justwatch.com/in/movie/send-help,7.2,1h 53min,A,United States,JioHotstar
104,Youth(2026),2026,"Comedy, Kids & Family, Romance, Drama, Dramedy",https://www.justwatch.com/in/movie/youth-2026,8.1,2h 20min,UA13+,India,Netflix

In [ ]:
# Save the filtered DataFrame as a CSV file
# The file will contain only movies with an IMDb rating of 7 or higher.
# Setting index=False prevents the DataFrame row index
# from being written as an extra column in the CSV file.

filtered_df.to_csv(
    "Filtered_Movies_Data.csv",
    index=False
)

# Display a confirmation message after the CSV file is successfully saved

print("Filtered_Movies_Data.csv saved successfully")

Filtered_Movies_Data.csv saved successfully