<a href="https://colab.research.google.com/github/ThirumalReddyPeddi/Numerical-Programming-in-Python---Web-Scraping.ipynb/blob/main/07_Data_Filtering_and_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Task 2 :- Data Filtering & Analysis**

In [ ]:
# Import the required libraries
# Pandas is used for data manipulation and analysis.
# datetime is used to work with date and time values.

import pandas as pd
from datetime import datetime

# Convert the 'Release_Year' column in the Movies DataFrame
# from text (string) format to numeric format.
# Any invalid or missing values will be converted to NaN.

movies_df["Release_Year"] = pd.to_numeric(
    movies_df["Release_Year"],
    errors="coerce"
)

# Convert the 'IMDb_Rating' column in the Movies DataFrame
# from text (string) format to numeric format.
# Invalid or missing values are converted to NaN.

movies_df["IMDb_Rating"] = pd.to_numeric(
    movies_df["IMDb_Rating"],
    errors="coerce"
)

# Convert the 'Release_Year' column in the TV Shows DataFrame
# from text (string) format to numeric format.
# Invalid or missing values are converted to NaN.

tv_shows_df["Release_Year"] = pd.to_numeric(
    tv_shows_df["Release_Year"],
    errors="coerce"
)

# Convert the 'IMDb_Rating' column in the TV Shows DataFrame
# from text (string) format to numeric format.
# Invalid or missing values are converted to NaN.

tv_shows_df["IMDb_Rating"] = pd.to_numeric(
    tv_shows_df["IMDb_Rating"],
    errors="coerce"
)

In [ ]:
# Step 2: Get the current year and calculate the cutoff year

current_year = datetime.now().year
cutoff_year = current_year - 2

In [ ]:
# Step 3: Filter Movies

filtered_movies_df = movies_df[
    (movies_df["Release_Year"] >= cutoff_year) &
    (movies_df["IMDb_Rating"] >= 7)
]

filtered_movies_df.head()

,Movie_Title,Release_Year,Genres,URLs,IMDb_Rating,Runtime,Age_Rating,Production_Country,OTT Streaming_Service
2,Kara(2026),2026.0,"Drama, Mystery & Thriller, Crime, Heist",https://www.justwatch.com/in/movie/kara,7.1,2h 41min,UA16+,India,Netflix
17,Marty Supreme(2025),2025.0,"Drama, Sport, Mystery & Thriller, Dramedy",https://www.justwatch.com/in/movie/marty-supreme,7.8,2h 29min,A,"Finland, United States",Apple TV Store
34,Dhurandhar The Revenge(2026),2026.0,"Action & Adventure, Crime, Mystery & Thriller",https://www.justwatch.com/in/movie/dhurandhar-...,8.7,3h 50min,A,India,JioHotstar
36,Hokum(2026),2026.0,"Horror, Horror Thriller",https://www.justwatch.com/in/movie/hokum-2026,8.0,1h 41min,A,"United Arab Emirates, United States, Ireland",Crunchyroll
38,The Punisher: One Last Kill(2026),2026.0,"Action & Adventure, Drama, Crime, Mystery & Th...",https://www.justwatch.com/in/movie/the-punishe...,7.1,51min,None,United States,JioHotstar

In [ ]:
# Step 4: Filter TV Shows

filtered_tv_shows_df = tv_shows_df[
    (tv_shows_df["Release_Year"] >= cutoff_year) &
    (tv_shows_df["IMDb_Rating"] >= 7)
]

filtered_tv_shows_df.head()

,TV_Show_Title,Release_Year,Genres,URLs,IMDb_Rating,Runtime,Age_Rating,Production_Country,OTT_Streaming_Service
1,Dutton Ranch,2026,"Western, Drama, Epic Western",https://www.justwatch.com/in/tv-show/dutton-ranch,8.4,48min,NaN,United States,JioHotstar
8,Resort,2026,"Comedy, Drama",https://www.justwatch.com/in/tv-show/resort,8.8,27min,UA16+,India,JioHotstar
19,Gyaarah Gyaarah,2024,"Drama, Fantasy, Science-Fiction, Modern Fantasy",https://www.justwatch.com/in/tv-show/gyaarah-g...,8.1,44min,A,India,Zee5
23,The Boroughs,2026,"Science-Fiction, Mystery & Thriller, Drama, Fa...",https://www.justwatch.com/in/tv-show/the-boroughs,7.4,46min,UA16+,United States,Netflix
24,Laughter Chefs Unlimited Entertainment,2024,"Comedy, Reality TV, Kids & Family, Bollywood",https://www.justwatch.com/in/tv-show/laughter-...,8.4,1h 6min,NaN,India,JioHotstar

In [ ]:
# Display the first 5 rows

movies_df.head()

,Movie_Title,Release_Year,Genres,URLs,IMDb_Rating,Runtime,Age_Rating,Production_Country,OTT Streaming_Service
0,Crush(2009),2009.0,"Horror, Drama, Horror Thriller, Mystery Thriller",https://www.justwatch.com/in/movie/crush-2009,4.2,1h 22min,None,Australia,Apple TV Store
1,Taya(2021),2021.0,"Mystery & Thriller, Crime, Drama, Romantic Thr...",https://www.justwatch.com/in/movie/taya-2021,4.7,1h 43min,None,Philippines,Amazon Video
2,Kara(2026),2026.0,"Drama, Mystery & Thriller, Crime, Heist",https://www.justwatch.com/in/movie/kara,7.1,2h 41min,UA16+,India,Netflix
3,Hai Jawani Toh Ishq Hona Hai(2026),2026.0,"Romance, Comedy",https://www.justwatch.com/in/movie/hai-jawani-...,NaN,2h 16min,UA16+,India,Crunchyroll
4,Stay Lost(2023),2023.0,Romance,https://www.justwatch.com/in/movie/stay-lost,NaN,12min,None,United States,Crunchyroll

In [ ]:
# Basic information about the dataset


movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Movie_Title            105 non-null    object
 1   Release_Year           96 non-null     float64
 2   Genres                 103 non-null    object
 3   URLs                   105 non-null    object
 4   IMDb_Rating            77 non-null     float64
 5   Runtime                103 non-null    object
 6   Age_Rating             43 non-null     object
 7   Production_Country     105 non-null    object
 8   OTT Streaming_Service  105 non-null    object
dtypes: float64(2), object(7)
memory usage: 7.5+ KB

In [ ]:
# Summary statistics

movies_df.describe(include="all")

,Movie_Title,Release_Year,Genres,URLs,IMDb_Rating,Runtime,Age_Rating,Production_Country,OTT Streaming_Service
count,105,96.000000,103,105,77.000000,103,43,105,105
unique,105,NaN,82,105,NaN,70,6,29,10
top,Crush(2009),NaN,"Drama, Emotional Drama",https://www.justwatch.com/in/movie/crush-2009,NaN,1h 31min,A,India,Crunchyroll
freq,1,NaN,7,1,NaN,4,15,34,35
mean,NaN,2020.885417,NaN,NaN,5.648052,NaN,NaN,NaN,NaN
std,NaN,6.732279,NaN,NaN,1.545078,NaN,NaN,NaN,NaN
min,NaN,2001.000000,NaN,NaN,2.700000,NaN,NaN,NaN,NaN
25%,NaN,2017.750000,NaN,NaN,4.500000,NaN,NaN,NaN,NaN
50%,NaN,2024.500000,NaN,NaN,5.500000,NaN,NaN,NaN,NaN
75%,NaN,2026.000000,NaN,NaN,6.800000,NaN,NaN,NaN,NaN
max,NaN,2026.000000,NaN,NaN,8.700000,NaN,NaN,NaN,NaN

In [ ]:
# Filter TV shows available on a specific streaming service

hotstar_shows = movies_df[
    movies_df["OTT Streaming_Service"].str.contains(
        "JioHotstar",
        case=False,
        na=False
    )
]
print(len(hotstar_shows))
print(hotstar_shows)

6
                                   Movie_Title  Release_Year  \
34                Dhurandhar The Revenge(2026)        2026.0
38           The Punisher: One Last Kill(2026)        2026.0
43   Vaazha II: Biopic of a Billion Bros(2026)        2026.0
57               Sambhavam Adhyayam Onnu(2026)        2026.0
95                               Hoppers(2026)        2026.0
100                            Send Help(2026)        2026.0

                                                Genres  \
34       Action & Adventure, Crime, Mystery & Thriller
38   Action & Adventure, Drama, Crime, Mystery & Th...
43                              Drama, Comedy, Dramedy
57   Fantasy, Mystery & Thriller, Drama, Psychologi...
95   Action & Adventure, Animation, Comedy, Kids & ...
100  Horror, Mystery & Thriller, Comedy, Horror Thr...

                                                  URLs  IMDb_Rating   Runtime  \
34   https://www.justwatch.com/in/movie/dhurandhar-...          8.7  3h 50min
38   https://www.justwatch.com/in/movie/the-punishe...          7.1     51min
43   https://www.justwatch.com/in/movie/vaazha-ii-b...          NaN  2h 42min
57   https://www.justwatch.com/in/movie/sambhavam-a...          7.3   2h 7min
95          https://www.justwatch.com/in/movie/hoppers          7.6  1h 44min
100       https://www.justwatch.com/in/movie/send-help          7.2  1h 53min

    Age_Rating Production_Country OTT Streaming_Service
34           A              India            JioHotstar
38        None      United States            JioHotstar
43       UA13+              India            JioHotstar
57       UA13+              India            JioHotstar
95        UA7+      United States            JioHotstar
100          A      United States            JioHotstar

In [ ]:
top_10 = movies_df.sort_values(
    by="IMDb_Rating",
    ascending=False
).head(10)

top_10[["Movie_Title", "IMDb_Rating"]]

                                           Movie_Title  IMDb_Rating
34                        Dhurandhar The Revenge(2026)          8.7
44                             Project Hail Mary(2026)          8.5
80   Demon Slayer: Kimetsu no Yaiba Infinity Castle...          8.4
50                                    Dhurandhar(2025)          8.3
71                              K.G.F: Chapter 2(2022)          8.2
29                              Deiva Thirumagal(2011)          8.2
104                                        Youth(2026)          8.1
72                                     Obsession(2026)          8.1
36                                         Hokum(2026)          8.0
17                                 Marty Supreme(2025)          7.8

## **Calculating Mean IMDB Ratings for both Movies and Tv Shows**

In [ ]:
movies_mean = movies_df["IMDb_Rating"].mean()
tv_shows_mean = tv_shows_df["IMDb_Rating"].mean()

print("Mean IMDb Rating for Movies:", round(movies_mean, 2))
print("Mean IMDb Rating for TV Shows:", round(tv_shows_mean, 2))

Mean IMDb Rating for Movies: 5.65
Mean IMDb Rating for TV Shows: 7.56

## **Analyzing Top Genres**

In [ ]:
# Top Genres for Movies

movie_genres = (
    movies_df["Genres"]
    .dropna()
    .str.split(", ")
    .explode()
)

# Count the occurrence of each genre in the dataset.
# The value_counts() function returns the frequency of each unique genre,
# sorted in descending order (most common genre first).

top_movie_genres = movie_genres.value_counts()

print(top_movie_genres)

Genres
Drama                     73
Romance                   36
Mystery & Thriller        31
Romantic Drama            23
Action & Adventure        21
Comedy                    18
Crime                     14
Emotional Drama           13
Horror                    12
Made in Europe             9
Horror Thriller            8
Bollywood                  7
Fantasy                    7
Science-Fiction            6
Action Thriller            5
Dramedy                    5
Mystery Thriller           4
History                    4
Romantic Thriller          4
Kids & Family              4
RomCom                     3
Music & Musical            3
Animation                  2
Sport                      2
Documentary                2
Biopics                    2
Heist                      1
Sports Drama               1
Monster                    1
Raunchy Comedy             1
Action Adventure           1
Sci-Fi Drama               1
Horror Comedy              1
Female Comedy              1
Psychological Thriller     1
Found Footage              1
Classic Japanese Anime     1
Music Biopics              1
Dark Crime                 1
Family Animation           1
Martial Art                1
Name: count, dtype: int64

In [ ]:
# Extract and analyze the genres present in the TV Shows DataFrame.

# Select the 'Genres' column from the DataFrame.
# Remove any missing (NaN) values to avoid errors during processing.
# Split the comma-separated genre strings into individual genres.
# Example:
# "Drama, Mystery, Thriller"
# becomes
# ["Drama", "Mystery", "Thriller"]
# The explode() function then creates a separate row for each genre.
tv_genres = (
    tv_shows_df["Genres"]
    .dropna()
    .str.split(", ")
    .explode()
)


top_tv_genres = tv_genres.value_counts()

# Display the frequency count of all TV show genres.
print("Top TV Show Genres:")
print(top_tv_genres)

Top TV Show Genres:
Genres
Drama                     87
Action & Adventure        38
Mystery & Thriller        32
Science-Fiction           31
Crime                     30
Comedy                    30
Fantasy                   23
Bollywood                 18
Animation                 15
Romance                   14
Classic Japanese Anime    11
Mystery Thriller          10
Horror                     8
Romantic Drama             6
Action Adventure           6
Kids & Family              5
Reality TV                 5
Action Thriller            5
Dramedy                    4
Organized Crime            4
Emotional Drama            4
Young Adult Drama          3
Period Drama               3
Sport                      3
Detective Crime            2
Epic                       2
Dark Crime                 2
Modern Fantasy             2
History                    2
Made in Europe             2
Heist                      2
Superhero                  2
Epic Fantasy               2
Western                    1
Epic Western               1
Based On A True Story      1
Cerebral                   1
RomCom                     1
Invasion                   1
Zombie                     1
Sci-Fi Drama               1
Monster                    1
Romantic Thriller          1
No Superhero               1
Psychological Drama        1
War & Military             1
Western Animation          1
Name: count, dtype: int64

In [ ]:
# Top Genres for TV Shows
tv_genres = (
    tv_shows_df["Genres"]
    .dropna()
    .str.split(", ")
    .explode()
)
# Count the occurrence of each genre in the dataset.
# The value_counts() function returns the frequency of each unique genre,
# sorted in descending order (most common genre first).

top_tv_genres = tv_genres.value_counts()

print(top_tv_genres)

Genres
Drama                     87
Action & Adventure        38
Mystery & Thriller        32
Science-Fiction           31
Crime                     30
Comedy                    30
Fantasy                   23
Bollywood                 18
Animation                 15
Romance                   14
Classic Japanese Anime    11
Mystery Thriller          10
Horror                     8
Romantic Drama             6
Action Adventure           6
Kids & Family              5
Reality TV                 5
Action Thriller            5
Dramedy                    4
Organized Crime            4
Emotional Drama            4
Young Adult Drama          3
Period Drama               3
Sport                      3
Detective Crime            2
Epic                       2
Dark Crime                 2
Modern Fantasy             2
History                    2
Made in Europe             2
Heist                      2
Superhero                  2
Epic Fantasy               2
Western                    1
Epic Western               1
Based On A True Story      1
Cerebral                   1
RomCom                     1
Invasion                   1
Zombie                     1
Sci-Fi Drama               1
Monster                    1
Romantic Thriller          1
No Superhero               1
Psychological Drama        1
War & Military             1
Western Animation          1
Name: count, dtype: int64

In [ ]:
# Top 5 Genres
print("Top 5 Movie Genres:")

# Display the five most frequently occurring genres in the Movies dataset.
print(top_movie_genres.head(5))

print("\nTop 5 TV Show Genres:")

# Display the five most frequently occurring genres in the TV Shows dataset.
print(top_tv_genres.head(5))

Top 5 Movie Genres:
Genres
Drama                 73
Romance               36
Mystery & Thriller    31
Romantic Drama        23
Action & Adventure    21
Name: count, dtype: int64

Top 5 TV Show Genres:
Genres
Drama                 87
Action & Adventure    38
Mystery & Thriller    32
Science-Fiction       31
Crime                 30
Name: count, dtype: int64

## **Finding Predominant Streaming Service**

In [ ]:
# Write Your Code here

In [ ]:
movie_streaming_counts = (
    movies_df['OTT Streaming_Service']
    .dropna()
    .str.split(", ")
    .explode()
    .value_counts()
)

print(movie_streaming_counts)

OTT Streaming_Service
Crunchyroll           35
JustWatch             18
Amazon Prime Video    15
Apple TV Store        10
Amazon Video          10
Netflix                8
JioHotstar             6
Zee5                   1
Plex Player            1
Sun Nxt                1
Name: count, dtype: int64

In [ ]:
# Most Predominant Streaming Service:

print("Predominant Streaming Service for Movies:")

# The idxmax() method returns the index label corresponding
# to the maximum value in the Series.
# In this case, it returns the OTT platform with the highest
# number of movie titles.
print(movie_streaming_counts.idxmax())


print("Number of Titles:", movie_streaming_counts.max())

Predominant Streaming Service for Movies:
Crunchyroll
Number of Titles: 35

In [ ]:
# For TV Shows
tv_streaming_counts = (
    tv_shows_df['OTT_Streaming_Service']
    .dropna()
    .str.split(", ")
    .explode()
    .value_counts()
)

print(tv_streaming_counts)

OTT_Streaming_Service
Netflix               27
Amazon Prime Video    24
Crunchyroll           22
JioHotstar            20
JustWatch              6
Zee5                   2
MX Player              2
Hoichoi                1
Apple TV Store         1
Name: count, dtype: int64

In [ ]:
# Most Predominant Streaming Service

print("Predominant Streaming Service for TV Shows:")
print(tv_streaming_counts.idxmax())
print("Number of Titles:", tv_streaming_counts.max())

Predominant Streaming Service for TV Shows:
Netflix
Number of Titles: 27

## **Task 3 :- Data Export**

In [ ]:
#saving final dataframe as Final Data in csv format

In [ ]:
movies_df.to_csv(
    "Final_Movies_Dataa.csv",
    index=False
)

print("Movies_Data.csv saved successfully")

Movies_Data.csv saved successfully

In [ ]:
tv_shows_df.to_csv(
    "Final_Tv_Show_Dataa.csv",
    index=False
)

print("CSV file saved successfully")

CSV file saved successfully

In [ ]:
#saving filter data as Filter Data in csv format

In [ ]:
filtered_df.to_csv(
    "Filtered_Movies_Dataa.csv",
    index=False
)

print("CSV file saved successfully")

CSV file saved successfully

In [ ]:
tv_filtered_df.to_csv(
    "Tv_Filtered_Dataa.csv",
    index=False
)

print("CSV file saved successfully")

CSV file saved successfully